config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

Myapp::Application.routes.draw do

  get "requests/registrarme" => "requests#registrarme"
  get "requests/quitarme" => "requests#quitarme"

  resources :user_in_requests

  resources :requests

  resources :courses

  resources :schedules

  resources :states

  get "sessions/new"
  get "users/new"
  get "home/index"
	get "users/usuario"

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "users/usuario" => "users#usuario", :as => "usuario"

constraints(AuthConstraint.new) do
	root :to => 'requests#rooturl', :as => "authenticated_root"
end

root :to => "sessions#new"
resources :users
resources :sessions

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :course_id, :schedule_id, :state_id
  belongs_to :schedule
  belongs_to :state
  belongs_to :course
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

def rooturl
	redirect_to requests_path
end

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
		if current_user
    @request = Request.new
		else
		redirect_to log_in_path
		end
  end

  # GET /requests/1/edit
  def edit
  end

	def yaEstoyInscrito course_id
		if current_user.id != 1
		clases = UserInRequest.where(:user_id => current_user.id)
		clases.each do|clase|
			if Request.find_by_id(clase.request_id).course_id == course_id
				return true
			end
		end
		end
		return false  
	end	

	def yaEstoyInscritoHorario schedule_id
		if current_user.id != 1
		clases = UserInRequest.where(:user_id => current_user.id)
		clases.each do|clase|
			if Request.find_by_id(clase.request_id).schedule_id == schedule_id
				return true
			end
		end
		end
		return false  
	end	

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
		@request.state_id = 1
    respond_to do |format|

			#Ya hay una request
  		if Request.where(:course_id => @request.course_id, :schedule_id => @request.schedule_id).count != 0
				#El usuario ya es parte de la request
				temp = Request.where(:course_id => @request.course_id, :schedule_id => @request.schedule_id)[0]
  			if UserInRequest.where(:user_id => current_user.id, :request_id => temp.id).count == 0
  				ur = UserInRequest.new
  	      ur.user_id = current_user.id
  	      ur.request_id = temp.id
  				ur.save
	        format.html { redirect_to "/requests", notice: 'Registrado con exito.' }
  			else
	        format.html { redirect_to "/requests/new", notice: 'Ya estabas registrado.' }
        end
			#No hay una request
			elsif yaEstoyInscrito @request.course_id
						format.html { redirect_to "/requests/new", notice: 'Ya estas registrado con la misma clase a otra hora, borra tu otro registro y prueba de nuevo.' }
			
			elsif yaEstoyInscritoHorario @request.schedule_id
						format.html { redirect_to "/requests/new", notice: 'Ya estas registrado a esa hora con otra clase, borra tu otro registro y prueba de nuevo.'}			

  		elsif @request.save
				ur = UserInRequest.new
        ur.user_id = current_user.id
        ur.request_id = @request.id
				ur.save
        format.html { redirect_to @request, notice: 'La propuesta fue creada exitosamente.' }
        format.json { render action: 'show', status: :created, location: @request }
      else
        format.html { render action: 'new' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'La propuesta ha sido actualizada.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end

  def registrarme
		@schedule_id = params[:schedule_id]
		@course_id = params[:course_id]
		@request_id = params[:request_id]
		if ( (yaEstoyInscrito (@course_id.to_i))	|| (yaEstoyInscritoHorario(@schedule_id.to_i)) )
			respond_to do |format|
  	  	format.html { redirect_to "/requests/", notice: 'Ya estas Registrado a esa Hora o en ese Curso!' }
			end
		else
	   	uir = UserInRequest.new
 	  	uir.user_id = current_user.id
 	  	uir.request_id = @request_id
 	  	uir.save
			respond_to do |format|
  	  	format.html { redirect_to "/requests/", notice: 'Registrado Exitosamente' }
			end
    end
  end

	def quitarme
		@request_id = params[:request_id]
		u = UserInRequest.where(:user_id => current_user.id, :request_id => @request_id)[0]
		if u != nil
		u.destroy
		u.save
		end
		redirect_to "/requests/", notice: 'Quitado de la propuesta'
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
			if current_user
      @request = Request.find(params[:id])
			else
			redirect_to log_in_path
			end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:course_id, :schedule_id, :state_id)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Clase %><br>
    <select name="request[course_id]">
      <% Course.all.each do |c| %>
        <option value="<%= c.id %>"><%= c.name %> — Req: <%=c.requirements%></option>
      <% end %>
    </select>
  </div>
  <div class="field">
    <%= f.label :Horario %><br>
    <select name="request[schedule_id]">
      <% Schedule.all.each do |s| %>
        <option value="<%= s.id %>"><%= s.name %></option>
      <% end %>
    </select>
  </div>
  <div class="field">
    <%= f.label :Estado %><br>
    <select name="request[state_id]">
      <% State.all.each do |e| %>
        <option value="<%= e.id %>"><%= e.name %></option>
      <% end %>
    </select>
  </div>
  <div class="actions">
    <%= f.submit 'Crear Propuesta' %>
  </div>
<% end %>


</section>
</div>

app/views/requests/_form_edit.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Estado %><br>
    <select name="request[state_id]">
      <% State.all.each do |e| %>
        <option value="<%= e.id %>"><%= e.name %></option>
      <% end %>
    </select>
  </div>
  <div class="actions">
    <%= f.submit 'Actualizar' %>
  </div>
<% end %>


</section>
</div>

app/views/requests/_form_new.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Clase %><br>
    <select name="request[course_id]">
      <% Course.all.each do |c| %>
        <option value="<%= c.id %>"><%= c.name %> — Req: <%=c.requirements%></option>
      <% end %>
    </select>
  </div>
  <div class="field">
    <%= f.label :Horario %><br>
    <select name="request[schedule_id]">
      <% Schedule.all.each do |s| %>
        <option value="<%= s.id %>"><%= s.name %></option>
      <% end %>
    </select>
  </div>

  <div class="actions">
    <input type=submit value="Crear Propuesta", onClick="if(confirm('Recuerde que esta clase solo se abrira si cuenta con 15 Alumnos'));">
  </div>
<% end %>

<p><%= notice %></p>
</section>
</div>

app/views/requests/edit.html.erb
<% if current_user %>
<div class="content-wrapper">
 <section class="content-header">

<h1>Editando propuesta</h1>

<%= render 'form_edit' %>

<%= link_to 'Mostrar', @request %> |
<%= link_to 'Regresar', requests_path %>
<% else %>
<%= controller.redirect_to log_in_path %>
<% end %>

app/views/requests/index.html.erb
<div class="content-wrapper">
 <section class="content-header">
<p id="notice"><%= notice %></p>
<% if current_user %>
<h1><u>Listado de Propuestas</u></h1>

<h2>Propuestas Iniciales</h2>
<table>
  <thead>
    <tr>
      <th>Clase</th>
      <th>Horario</th>
      <th>Estado</th>
      <th>Registrados</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @uir1 = UserInRequest.all.where(user_id:1).each do |inicial| %>
      <% @requestito = Request.where(id: inicial.request_id).each do |request| %>
        <tr>
	  <td><%= request.course.name %></td>
	  <td><%= request.schedule.name %></td>
	  <td><%= request.state.name %></td>
          <td><%= (UserInRequest.where(:request_id => request.id).count) -1%></td>
          <td><%= link_to 'Mostrar', request %></td>
	    <% if userIsCoordinator %>
              <td><%= link_to 'Editar', edit_request_path(request) %></td>
	      <td><%= link_to 'Borrar', request, method: :delete, data: { confirm: '¿Borrar propuesta?' } %></td>
            <% end %>
            <% if UserInRequest.where(:user_id => current_user.id, :request_id =>request.id).count == 0 %>
            <td><%= link_to 'Registrarme', {:controller => :requests, :action=>'registrarme', :request_id => request.id ,:course_id => request.course_id, :schedule_id => request.schedule_id} %></td>
            <% end %>
	    <% if UserInRequest.where(:user_id => current_user.id, :request_id =>request.id).count == 1 %>
        	<td><%= link_to 'Quitarme', '/requests/quitarme?request_id='+request.id.to_s %></td>
	    <% end %>
         </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<h2>Propuestas en las que estoy yo</h2>
<table>
	<thead>
		<tr>
			<th>Clase</th>
      		<th>Horario</th>
      		<th>Estado</th>
      		<th>Registrados</th>
      		<th></th>
      		<th></th>
      		<th></th>
      		<th></th>
		</tr>
	</thead>

	<tbody>
		<% @uir1 = UserInRequest.all.where(user_id: current_user).each do |inicial| %>
      	<% @requestito = Request.where(id: inicial.request_id).each do |request| %>
        <tr>
	  	<td><%= request.course.name %></td>
	  	<td><%= request.schedule.name %></td>
	  	<td><%= request.state.name %></td>
        <% if UserInRequest.where(:request_id => request.id, :user_id => 1).count == 1%>
          <td><%= (UserInRequest.where(:request_id => request.id).count) -1%></td>
        <% else%>
          <td><%= (UserInRequest.where(:request_id => request.id).count) %></td>
        <% end %>
        <td><%= link_to 'Mostrar', request %></td>
	    <% if userIsCoordinator %>
        	<td><%= link_to 'Editar', edit_request_path(request) %></td>
	      	<td><%= link_to 'Borrar', request, method: :delete, data: { confirm: '¿Borrar propuesta?' } %></td>
    	<% end %>
    	<% if UserInRequest.where(:user_id => current_user.id, :request_id =>request.id).count == 0 %>
            <td><%= link_to 'Registrarme', {:controller => :requests, :action=>'registrarme', :request_id => request.id} %></td>
        <% end %>
	    <% if UserInRequest.where(:user_id => current_user.id, :request_id =>request.id).count == 1 %>
        	<td><%= link_to 'Quitarme', '/requests/quitarme?request_id='+request.id.to_s %></td>
	    <% end %>
        </tr>
      	<% end %>
    	<% end %>
	</tbody>
</table>

<h2>Propuestas por alumnos</h2>
<table>
  <thead>
    <tr>
      <th>Clase</th>
      <th>Horario</th>
      <th>Estado</th>
      <th>Registrados</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      <% @request = Request.all.each do |request| %>
	<% existe = false %>
	  <% UserInRequest.where(request_id: request.id).each do |uir| %>
	   <% if uir.user_id == 1 %>
	    <% existe = true %>
	   <% end %>
	  <% end %>
	<% if existe == false %>
      <tr>
	<td><%= request.course.name %></td>
	<td><%= request.schedule.name %></td>
	<td><%= request.state.name %></td>
        <td><%= (UserInRequest.where(:request_id => request.id).count) %></td>
        <td><%= link_to 'Mostrar', request %></td>
				<% if userIsCoordinator %>
        	<td><%= link_to 'Editar', edit_request_path(request) %></td>
	        <td><%= link_to 'Borrar', request, method: :delete, data: { confirm: '¿Borrar propuesta?' } %></td>
				<% end %>
        <% if UserInRequest.where(:user_id => current_user.id, :request_id =>request.id).count == 0 %> 
          <td><%= link_to 'Registrarme', {:controller => :requests, :action=>'registrarme', :request_id => request.id , :course_id => request.course_id, :schedule_id => request.schedule_id} %></td>				
				<% end %>

        <% if UserInRequest.where(:user_id => current_user.id, :request_id =>request.id).count == 1 %>
        	<td><%= link_to 'Quitarme', '/requests/quitarme?request_id='+request.id.to_s %></td>
	<% end %>
      </tr>
	<% end %>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Nueva propuesta', new_request_path %>

<% else %>
<h1>Listado de propuestas</h1>

<h2>Propuestas Iniciales</h2>
<table>
  <thead>
    <tr>
      <th>Clase</th>
      <th>Horario</th>
      <th>Estado</th>
      <th>Registrados</th>
    </tr>
  </thead>

  <tbody>
    <% @uir1 = UserInRequest.all.where(user_id:1).each do |inicial| %>
      <% @requestito = Request.where(id: inicial.request_id).each do |request| %>
        <tr>
	  <td><%= request.course.name %></td>
	  <td><%= request.schedule.name %></td>
	  <td><%= request.state.name %></td>
          <td><%= (UserInRequest.where(:request_id => request.id).count) -1%></td>
         </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<h2>Propuestas por alumnos</h2>
<table>
  <thead>
    <tr>
      <th>Clase</th>
      <th>Horario</th>
      <th>Estado</th>
      <th>Registrados</th>
    </tr>
  </thead>

  <tbody>
      <% @request = Request.all.each do |request| %>
	<% existe = false %>
	  <% UserInRequest.where(request_id: request.id).each do |uir| %>
	   <% if uir.user_id == 1 %>
	    <% existe = true %>
	   <% end %>
	  <% end %>
	<% if existe == false %>
      <tr>
	<td><%= request.course.name %></td>
	<td><%= request.schedule.name %></td>
	<td><%= request.state.name %></td>
        <td><%= (UserInRequest.where(:request_id => request.id).count) %></td>
      </tr>
	<% end %>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/requests/new.html.erb
<div class="content-wrapper">
 <section class="content-header">

<h1>Nueva propuesta</h1>

<%= render 'form_new' %>

<%= link_to 'Regresar', requests_path %>

app/views/requests/registrarme.html.erb
test

<%= @test %>

app/views/requests/show.html.erb
<% if current_user %>
<div class="content-wrapper">
 <section class="content-header">

<p id="notice"><%= notice %></p>

<p>
  <strong>Clase:</strong>
  <%= @request.course.name %>
</p>

<p>
  <strong>Requisitos:</strong>
  <%= @request.course.requirements %>
</p>

<p>
  <strong>Requisitos recomendados:</strong>
  <%= @request.course.recommended_requirements %>
</p>

<p>
  <strong>Horario:</strong>
  <%= @request.schedule.name %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @request.state.name %>
</p>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Nombre</th>
      <th>Cuenta</th>
      <%if userIsCoordinator == true%>
      <th>Telefono</th>
      <% end %>
      <th>Informacion Adicional</th>
    </tr>
  </thead>

  <tbody>
    <% UserInRequest.where(:request_id => @request.id).each do |uir| %>
			<% u = User.find_by_id(uir.user_id) %>
	<% if u.id != 1 %>      
  <tr>
        <td><%= u.email %></td>
        <td><%= u.name %></td>
        <td><%= u.cuenta %></td>
        <%if userIsCoordinator == true%>
        <td><%= u.telefono %></td>
        <% end %>
        <td><%= u.informacion_adicional %></td>
			</tr>
	<% end %>
    <% end %>
  </tbody>
</table>

<% if userIsCoordinator %>
	<%= link_to 'Editar', edit_request_path(@request) %> |
<% end %>
<%= link_to 'Regresar', requests_path %>



</section>
</div>
<% else %>
<%= controller.redirect_to log_in_path %>
<% end %>